@startuml
skinparam backgroundColor #fdfdfd
skinparam ActivityFontSize 12
skinparam ArrowColor red

title Proceso Clase_Gato_Hereda_Mascota

start

:Definir hambre, felicidad, energia Como Entero;
:Definir opcion Como Entero;

:hambre <- 50;
:felicidad <- 50;
:energia <- 80;

repeat
  :Limpiar Pantalla;
  :Escribir 'ACCIONES PARA EL GATO:';
  :Escribir '1. Llamar METODO comer()';
  :Escribir '2. Llamar METODO jugar()';
  :Escribir '3. Llamar METODO dormir()';
  :Escribir '4. Salir';
  :Escribir 'Seleccione una opcion:';
  
  :Leer opcion;

  if (opcion=1) then (V)
    :Escribir 'Comiendo Atún en el plato de la Sala.';
    :hambre <- hambre-25;
    :Escribir '¡Miau! El gato ronronea.';
    :Escribir 'Presione una tecla para continuar...';
    :Esperar Tecla;
  else (F)
    if (opcion=2) then (V)
      :Escribir 'Atrapando el Puntero Láser.';
      :felicidad <- felicidad+30;
      :energia <- energia-25;
      :Escribir '¡Miau! El gato ronronea.';
      :Escribir 'Presione una tecla para continuar...';
      :Esperar Tecla;
    else (F)
      if (opcion=3) then (V)
        :Escribir 'Cambiando interfaz: Mostrando Caja de cartón.';
        :energia <- 100;
        :Escribir 'Presione una tecla para continuar...';
        :Esperar Tecla;
      else (F)
        if (opcion=4) then (V)
          :Escribir 'Saliendo del simulador del Gato...';
        else (F)
          :Escribir 'Opcion no valida.';
          :Esperar 1 Segundos;
        endif
      endif
    endif
  endif

repeat while (opcion=4) is (F)

:FinProceso;

stop
@enduml
